### PR TITLE
Default colors to false on Windows

### PR DESCRIPTION
**Pull request by damieng**
Standard Windows shells do not support changing the color using ANSI codes so default to off for now.  (Windows 10 has some improvements coming that may help)

Currently shows this with colors switched on which is quite unreadable:

```
←[92m ←[0m←[32m 2 passing←[0m←[90m (1s)←[0m
←[36m ←[0m←[36m 1 pending←[0m
←[31m  4 failing←[0m
```

### CODE REVIEW

**Comment by Alhadis** [comment]
Shouldn't libuv be intercepting those with native syscalls?

**Comment by damieng** [comment]
No idea but it's definitely not working on Windows.

**Comment by Alhadis** [comment]
That's really strange. Are you using PowerShell, or the normal command prompt?

I tested this on a virtualised Win7 installation:

~~~js
#!/usr/local/bin/node --es_staging
"use strict";

process.stdout.write(`
	\x1B[38;5;1m G'DAY WORLD. \x1B[0m
`);
~~~

... and the escape sequences degraded fine:

screen shot 2017-04-07 at 1 14 03 am

When running Mocha, I did note the ticks displayed in the spec-feedback were mangled, but that's probably an encoding issue:

Figure 2

**Comment by damieng** [comment]
I took your sample and that works just fine here too.  

Do  you get color output okay from Mocha?  Your screenshot only shows it in mono.

I'm actually using Cmdr.net but it supports xterm and ANSI X3.64 and works fine with every other tool I've used and your sample.

**Comment by Alhadis** [comment]
Oh! I forgot I [disabled highlighting](https://github.com/Alhadis/Atom-Mocha/blob/master/lib/main.js#L290) for streams not connected to a terminal (so `atom -t spec > results.txt` won't generate a file filled with garbage).

Don't know if that might be affecting the output on Windows or not... :\

**Pull request merged**
